language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install coverage coveralls --use-mirrors

script: coverage run --branch --source=names setup.py test

after_success: coveralls
